# Generated by Django 3.0.5 on 2020-04-05 19:36

import comics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=50)),
                ('tag_type', models.CharField(choices=[(comics.models.TagType['keyword'], 'keyword'), (comics.models.TagType['author'], 'author')], default='keyword', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('content', models.CharField(max_length=500)),
                ('tags', models.ManyToManyField(to='comics.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
