# Generated by Django 3.0.5 on 2020-04-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('keyword', 'keyword'), ('author', 'author')], default='keyword', max_length=10),
        ),
    ]
