# Generated by Django 3.0.5 on 2020-04-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_auto_20200405_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
