# Generated by Django 3.0.5 on 2020-04-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_comicsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicsource',
            name='tags',
            field=models.ManyToManyField(blank=True, to='comics.Tag'),
        ),
    ]
