# Generated by Django 3.0.5 on 2020-04-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_comicsource_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
